In [5]:
import random
import numpy as np

arreglo = np.random.randint(0, 100, size=(3, 3))

print(arreglo)

[[81 12 65]
 [73 17 74]
 [77 89 41]]


In [10]:
import numpy as np

promedio = np.mean(arreglo)
suma = np.sum(arreglo)
mayor = np.max(arreglo)
menor = np.min(arreglo)
diagonal = arreglo.diagonal()

print("Promedio de los elementos:", promedio)
print("Suma de los elementos:", suma)
print("Elemento mayor:", mayor)
print("Elemento menor:", menor)
print("Elementos de la diagonal principal:", diagonal)

Promedio de los elementos: 58.77777777777778
Suma de los elementos: 529
Elemento mayor: 89
Elemento menor: 12
Elementos de la diagonal principal: [81 17 41]


In [15]:
import numpy as np

arreglo = np.zeros((3, 3))

np.fill_diagonal(arreglo, [1, 2, 3])

print(arreglo)

[[1. 0. 0.]
 [0. 2. 0.]
 [0. 0. 3.]]
